// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeADAqu0qYZEAW12w9XTxGJfnYgbK_XDA',
    appId: '1:818309918051:web:5d8af3ba6deafcc0847756',
    messagingSenderId: '818309918051',
    projectId: 'first-project-evently-app',
    authDomain: 'first-project-evently-app.firebaseapp.com',
    storageBucket: 'first-project-evently-app.firebasestorage.app',
    measurementId: 'G-MZD1SZB6F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRGWR4TgSifklf9Ac4wwsmUdm027rYrnw',
    appId: '1:818309918051:android:c3230bdddcda404e847756',
    messagingSenderId: '818309918051',
    projectId: 'first-project-evently-app',
    storageBucket: 'first-project-evently-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr1UueKekGMi7zsDyNtt-pXIdFjDvy7wk',
    appId: '1:818309918051:ios:fd5e0ef03fc3cfe7847756',
    messagingSenderId: '818309918051',
    projectId: 'first-project-evently-app',
    storageBucket: 'first-project-evently-app.firebasestorage.app',
    iosBundleId: 'com.example.evantlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr1UueKekGMi7zsDyNtt-pXIdFjDvy7wk',
    appId: '1:818309918051:ios:fd5e0ef03fc3cfe7847756',
    messagingSenderId: '818309918051',
    projectId: 'first-project-evently-app',
    storageBucket: 'first-project-evently-app.firebasestorage.app',
    iosBundleId: 'com.example.evantlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeADAqu0qYZEAW12w9XTxGJfnYgbK_XDA',
    appId: '1:818309918051:web:46d48ea26a619234847756',
    messagingSenderId: '818309918051',
    projectId: 'first-project-evently-app',
    authDomain: 'first-project-evently-app.firebaseapp.com',
    storageBucket: 'first-project-evently-app.firebasestorage.app',
    measurementId: 'G-WWJ47QN7S9',
  );
}
